[package]
name = "financial-planning"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
actix = "0.12.0"
actix-rt = "2.8.0"
tokio = { version = "1.43.0", features = ["fs"] }
csv-async = "1.3.0"